apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname-system-msi
spec:
  provider: azure
  secretObjects:
    - secretName: mysecret
      type: Opaque
      data:
        - objectName: database
          key: key1
        - objectName: password
          key: key2
        - objectName: user
          key: key3
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"    
    userAssignedIdentityID: ""     
    keyvaultName: tmpkeyvl   
    cloudName: "AzurePublicCloud"
    objects:  |
      array:
        - |
          objectName: database
          objectType: secret
        - |
          objectName: password
          objectType: secret      
        - |
          objectName: user
          objectType: secret
    tenantId: b72e8a3a-e39b-45bb-8ed3-e1b67429f27b
